### ISSUE TITLE
FR pgconvert: optional second filename to specify output file

### ISSUE THREAD

**Issue by GitMensch** [ostash/perfgrind#11]
... ideally also for pgcollect

**Comment by GitMensch** [comment]
I _think_ I should be able to handle that, possibly providing resources for you to work on the more complicated #4.

Implementation questions:
What do you think of an option `-l` to specify the log file for pgcollect? This would get everything that is currently placed in stdout.
For pgcollect both the log file and the output file would be an attribute of the state.
For pgconvert the output file stream would be an attribute of Params.

Do you agree?
If the task is clear I'd work on that next (assign the issue to me if you like to).

**Comment by ostash** [comment]
`-l` is hardly useful, as pgcollect/pgreport prints almost nothing on stdout/stderr. Anyway, we can discuss this as a separate feature.

There is no need to add output file name to the state, only options parsing needs to be adjusted for pgcollect, the file name never leaves `prepareState` function.

For pgconvert, you can add somemthing like
```c++
std::ostream& Params::getOutputStream()
{
  if (outputFile)
    return outputFile
  return std::cout;
}
```
where `Params::outputFile` is `std::ofstream`.

**Comment by ostash** [comment]
One more thing to consider: `pgconvert` has input file, and `-i` is already used for enabling assembler instructions dumping. Now I'm wonder wouldn't it be better just consider second file name parameter as output, without `-o` option?

This way we can leave `pgcollect` as is.

**Comment by GitMensch** [comment]
That's a design decision. Taken.

**Comment by ostash** [comment]
> That's a design decision. Taken.

I'm trying to be very open to my community :) Especially when there is the single person in it :)

BTW, how did you find this repo at all?

**Comment by GitMensch** [comment]
> BTW, how did you find this repo at all?

**short answer:**

searching hard for "perf callgrind", likely via duckduckgo :-)

**detailed answer aka "my history":**

According to my search there is no working conversion tool that "just works out of the box" so far (that's something I'll likely inspect again at some point), the most promising I've found was an old kernel patch ["callgrind conversion tool"](https://www.mail-archive.com/linux-kernel@vger.kernel.org/msg408477.html) and perf2calltree.py that was [suggested to kcachegrind](https://phabricator.kde.org/D21306) originating in https://github.com/milianw/linux/commit/8b964dfc731ef55f592010d804b56bb61ab57a67; neither one of the kernel patches ever landed, nor the contribution to kcachegrind (which I did not get to work - always got python errors when executing `perf script -s perf2calltry.py`), so I've gone with the one of my findings that at least "somehow" worked on a testing machine: perfgrind.
The reason to stay was likely because of #1 being solved quite fast. Then found perfgrind not working on the actual dev environment, but got it solved myself with your help in #7. To distribute it better (others will do that when I give the go and we may do this on customer machines as well [something that from the above only the perf2calltree.py may allow because people won't build the matching kernel tools ins a patched versoion for that) docs and make/install procedure was necessary, which is now solved by #12, too.

**things to come**:

For being useful for the environments where I actually do want to trace #8 (something I'm likely to end before start of next week) and #4 (likely done via the streaming functions of libzstd, I still hope you get to that) are necessary (ideally plus a tag/release afterwards [reminder: you may still want to [post-tag](https://stackoverflow.com/questions/4404172/how-to-tag-an-older-commit-in-git) 0.3.0]). We'll see how that works out.

Other than that I'll likely get back to perf2calltree.py (at least my python is better than my perl, but that's not hard) and because I'm now interested in that whole topic will get back to the kernel patches and _may_ send my first one based on those "upstream", possibly next year.

**Comment by ostash** [comment]
LOL, I know this thread with Linux kernel patch, there is even my message [there](https://www.mail-archive.com/linux-kernel@vger.kernel.org/msg409496.html) :)

So it looks like situation haven't changed much since time I created perfgrind, there are no tools for working with Linux performance events in KCachegrind. And I must admit that KCachegrind is quite nice and easy tool.

There is Intel VTune actually and it is almost perfect. It allows to profile from every point of view, per thread, per applicaton, focus on specific parts of code. Really great tool.

**Comment by GitMensch** [comment]
> So it looks like situation haven't changed much since time I created perfgrind, there are no tools for working with Linux performance events in KCachegrind.

That was what I've mentioned, but actually I stand corrected. What does work is:

* record via perf (and you can actually limit the recorded events, reducing the size and io)
* convert the data to callgrind format by `perf script -s perf2calltree.py perf.data > callgrind.out.perf.data` (note: needs python enabled perf, potentially a correct manual setting for `PERF_EXEC_PATH` and the [perf2calltree.py script](https://phabricator.kde.org/D21306#change-JlDVCKnSpKlO))
* open the result in kcachegrind

Note: The issue with that script is that it does not include correct line references (they are post-resolved from the symbol name using `addr2line` only, so all calling "looks" to happen in the first line of the function); the "callchain" key of the event includes ip`s which _should_ be translatable to actual source line - but I have no idea how this may be done.
Similar there is no option similar to `--dump-instr` (as soon as the ip is translated that should be doable, too).
Minor issue it currently does not contain an entry for the command line (so that's shown as "empty"). There definitely should be a way to get that...

The parts that you get "for free" already: full list of functions with right instruction count incl/self and a working visual call stack.
Instruction view is empty, source only shows the function "prototype".

**Comment by ostash** [comment]
Ok, sounds that my perfgrind is stil superior :)
