### ISSUE TITLE
Should PLT hits be counted "special"?

### ISSUE THREAD

**Issue by GitMensch** [ostash/perfgrind#13]
I've seen ab01a438bea15c2636f3514de4c89196417360fc but am not sure how the "before" and "after" looks like (I know, I could checkout the old version and just test...), so this may or may not have be different in old versions.

In any case when inspecting generated callgrind files I see quite an amount of `func@plt` entries (which possibly only happens when tracing with a high frequency).
If traced via callgrind those function lookups are not shown, it _seems_ that the collection via perfparser attributes some executions that are done in the real function in a plt version (but that would need a deeper check to verify).

Question: Should these be shown? I _think_ the ideal version would be to count them as if they would have been finished with calling (= show the real function/module instead of the callers' `func@plt` version; but I'm not sure that this is even possible. If not, should they be directly attributed to the caller (which could be chosen by the user if #10  is implemented with `--collect=*@plt`) or do you consider the current version to be the most reasonable?

**Comment by GitMensch** [comment]
> the first hit to PLT goes through dynamic linker symbol resolver, and generally speaking, I want to see time spend there.

So "close as not planned" and people may use #10 (if/when that is added)?

**Comment by ostash** [comment]
Yes, probably I'm not going to work on this :)
