### ISSUE TITLE
Can we get rid of the 10+ year old branches?

### ISSUE THREAD

**Issue by GitMensch** [ostash/perfgrind#15]
0.1 and 0.2 are long gone...

**Comment by ostash** [comment]
We do we need to remove them? This is history :)

**Comment by GitMensch** [comment]
My personal understanding is that history is one of the reasons for tags - and those do exist and point to the exact same commit, while branches are places to work at things and it doesn't looks like someone will work in those branches.

Feel free to close this issue with either deleting them or not.
... and maybe post-add a 0.3 version, for example at 9b1a75f090cc64866eba7be7ee4368296ea6cba1 (before this year's round started).

**Comment by GitMensch** [comment]
Please add the tag for 0.3 from its branch. Thanks!

**Comment by ostash** [comment]
> Please add the tag for 0.3 from its branch. Thanks!

Done.
