### ISSUE TITLE
FR: GitHub metadata - "About"

### ISSUE THREAD

**Issue by GitMensch** [ostash/perfgrind#18]
Please go to the main page of this GitHub repo, then click right next to "about".

I suggest to use the following short description:

> perfgrind - tools for collecting samples from Linux performance events subsystem and converting profiling data to callgrind format, allowing it to be read with KCachegrind

and following tags (you need to actually enter one by one):

> linux-kernel perf profiling callgrind kcachegrind callgraph

and lastly disable "packages"

For the result see https://github.com/GitMensch/perfgrind on the right side.

**Comment by ostash** [comment]
Done
