### ISSUE TITLE
Question: does this repo contain kernel code?

### ISSUE THREAD

**Issue by GitMensch** [ostash/perfgrind#19]
Mainly asking because of the license notice...

If yes: which?
If not: Would you consider to make this repo GPLv3+ or at least GPLv2+?

**Comment by ostash** [comment]
Yes, but probably only this snippet:
https://github.com/ostash/perfgrind/blob/337ba036c887a8ea80e70c21a2cae64d94597389/pgcollect.c#L376-L383

**Comment by GitMensch** [comment]
One could argue that this single define is likely not significant for the program's (and only one of three programs) copyright / license.

In general: Would you consider to make perfgrind available under GPLv3+ or at least GPLv2+?

**Comment by ostash** [comment]
Well, I wanted to be on the safe side :) Does it block you in any way to stay with GPLv2?

**Comment by GitMensch** [comment]
Nope, I mostly wanted to be sure where this stands. Last question: Do you want to keep the additional notices in COPYING or would you be fine with having a note in the README (already done) and in the the actual source code (something I'd PR in, if you're ok with it)?

**Comment by ostash** [comment]
I feel like having all the info COPYING is fine. What are the benefits in duplicating that other places?

**Comment by GitMensch** [comment]
The README is just the place the people look at. Having a note which parts come from where would be good, I _think_ this commonly would belong to an AUTHORS file. If you are fine with it I'd like to add that.

No matter on your decision (and therefore the [not] addition of the file): Do you remember which parts of the code come from elfutils, too?

**Comment by ostash** [comment]
I think this project is too smal for having AUTHORS. Borrowed code is marked in comments,  see `AddressResolverPrivate::setOriginalBaseAddress`
