### ISSUE TITLE
Can't create performance event file descriptor: No such file or directory

### ISSUE THREAD

**Issue by GitMensch** [ostash/perfgrind#2]
Testing on current Debian worked fine, testing on another machine (RHEL 8.5) raised this error.
https://github.com/ostash/perfgrind/blob/9b1a75f090cc64866eba7be7ee4368296ea6cba1/pgcollect.c#L307-L314

As `perf record -o perf.data --call-graph dwarf,8192 -z` worked fine I have no idea what to check, do you have any clue why that system call does not work here?

**Comment by ostash** [comment]
I believe you don't have access to perf_events in a way pgcollect wants. Please, check /proc/sys/kernel/perf_event_paranoid setting.

**Comment by GitMensch** [comment]
That's on `-1`, otherwise the tracing via plain `perf` won't work either; I even tested with `sudo` - no luck,

Note: tracing with `perf record -o perf.data --call-graph dwarf,8192 -z --aio` without sudo raises a warning; while this should not be related "because sudo doesn't work with pgprof" I'm adding that info here for full info:

~~~

WARNING: Kernel address maps (/proc/{kallsyms,modules}) are restricted,
check /proc/sys/kernel/kptr_restrict and /proc/sys/kernel/perf_event_paranoid.

Samples in kernel functions may not be resolved if a suitable vmlinux
file is not found in the buildid cache or in the vmlinux path.

Samples in kernel modules won't be resolved at all.

If some relocation was applied (e.g. kexec) symbols may be misresolved
even with a suitable vmlinux or kallsyms file.

Couldn't record kernel reference relocation symbol
Symbol resolution may be skewed if relocation was used (e.g. kexec).
Check /proc/kallsyms permission or run as root.
~~~

**Comment by ostash** [comment]
pgcollect explictly skips samples from kernel, so this is not an issue.

I need to find RHEL8 box to test. Are you attaching to the existing process via PID or forking from pgcollect?

**Comment by ostash** [comment]
Is your RHEL8 machine virtual? pgcollect wants to use hardware events, without trying to fall back to a software ones.

What does `perf list` show?

**Comment by GitMensch** [comment]
> Is your RHEL8 machine virtual?

Yes, and it seems that there's no way to enable hardware virtualization there.

>  pgcollect wants to use hardware events, without trying to fall back to a software ones.

I see . that seems like a difference to `perf record`. If possible please add the fallback (and ideally a switch so testing that is feasible also on a "real" machine). If that seems to not be possible then please try to hint at this in the error message and document that in the README... or do the second for now and add a new issue to handle the first later, if it is likely to be too much work for now.

**Comment by ostash** [comment]
Yeah, I wrote this tool to collect "good" profiles, and using software events looked like a bad idea. But support is actually in the code, it is just commented out:

https://github.com/ostash/perfgrind/blob/9b1a75f090cc64866eba7be7ee4368296ea6cba1/pgcollect.c#L287-L291

**Comment by GitMensch** [comment]
I see. I'm working on a PR to use these depending on a command line switch "s" "use software events" and will report back (from all the issues I've raised that is the one I feel most comfortable to do myself).
