### ISSUE TITLE
bug in pgcollect: `--` not handled correctly; overwriting executables

### ISSUE THREAD

**Issue by GitMensch** [ostash/perfgrind#21]
If pgcollect does not find and output file name it leaks to after `--` which should always stop parsing.
Example:

result:
~~~
$> perfgrind/pgcollect -sF 8192 -- myprog myoption
Setting frequency to 8192
Going to profile process with PID 2561483: myoption
Can't exec new process: No such file or directory
Collection stopped.
Waked up 8 times
Sythetic mmap events: 0
Real mmap events: 0
Sample events: 0
Total 0 events written
~~~

and `myprog` being zero bytes afterwards (handled as output filename).

**Comment by ostash** [comment]
I confirm the bug.

**Comment by ostash** [comment]
Fixed via 0b50044e5bce4f8c911c358f1eb65d47e851d8d3

**Comment by GitMensch** [comment]
You may want to force-push a change to fix the typo

```diff
-  // We still a command to run for non-pid mode
+  // We still need a command to run for non-pid mode
```

and in theory all those error messages could be checked in `make check`, too ;-)

**Comment by ostash** [comment]
Done
