### ISSUE TITLE
FR: create debian package

### ISSUE THREAD

**Issue by GitMensch** [ostash/perfgrind#22]
This may be a "long term" issue, also given that the build itself is relative easy.

Nonetheless an "official" debian package is very likely to "reach out" to new users, also because of debian packages being a common "upstream" for debian-based distributions.

A point to start is possibly the "Debian Handbook" [Learning to Make Packages](https://www.debian.org/doc/manuals/debian-handbook/sect.becoming-package-maintainer.en.html#id-1.18.7.5).

**Comment by ostash** [comment]
Well, I never ran a Debian or Ubuntu (and I don't like them :)). Additionally, this raises a lot of questions - why debian package, why not rpm, which distribution to target, etc.

I can probably drop an Gentoo ebuild, as this I'm actually using for long years.

From other point of view, if user needs perfgrind, this means he/she is experienced enough to compile software (I can't imagine a non-developer analyzing call graph in KCachegrind). Such people have their compilers installed and know how to issue `make`.

Summary: I'm not going to do that :), but I won't be hard rejecting the contribution. (There will be a little pushback though, as such contribution requires me to install some Debian-based distro for testing the contribution. And I'm a developer, so I'm very lazy :))
