### ISSUE TITLE
Failing to start collection with mmap error

### ISSUE THREAD

**Issue by diehard2** [ostash/perfgrind#26]
Hi, I'm trying to get this to work. I'm on AlmaLinux 8 and its a relatively locked down server. I'm seeing

Can't mmap perf events: Operation not permitted perfgrind

Any tips or permissions I have to adjust are appreciated.

**Comment by ostash** [comment]
Hello,

To collect with hardware counters you may have to adjust the kernel parameter perf_event_paranoid as root.

See https://man7.org/linux/man-pages/man2/perf_event_open.2.html for the details.

**Comment by diehard2** [comment]
thanks for the reply @ostash! I have adjusted 

kernel.perf_event_paranoid=0 and kernel.kptr_restrict=0  and I'm still getting that mmap error. perf itself is working perfectly with these settings and ` perf record -p `

Would really like to be able to use this, but I'm not going to be able to get full sudo. Even those permissions are pushing what I can get away with. Thanks for any help

**Comment by ostash** [comment]
Can you provide output of `perf list`?

**Comment by diehard2** [comment]
when generating the output file I do get  a 

"Error: failed to open tracing events directory"

since I don't have root

[output.txt](https://github.com/ostash/perfgrind/files/15503276/output.txt)

**Comment by ostash** [comment]
Hm, this is a bit weird. If `perf record` works, than `pgcollect` should work as well. Maybe something like SELinux (or some other Linux security module) is blocking the access. Unfortunately, this is out of `perfgrind` control.
