### ISSUE TITLE
FR: pgconvert from `perf record` created file

### ISSUE THREAD

**Issue by GitMensch** [ostash/perfgrind#3]
Ideally I'd like to pgconvert profiles coming directly from
`LD_LIBRARY_PATH=. perf record -o perf.data --call-graph dwarf,8192 -z --aio --sample-cpu ./main`.

_Originally posted by @GitMensch in https://github.com/ostash/perfgrind/issues/1#issuecomment-1314403037_

Is this possible or can be added? Either directly into `pgconvert` or as separate tool like `pdatagconvert`?

**Comment by ostash** [comment]
Well, one of the reason I wrote own pgcollect was the fact that data file from 'perf' tool was too complicated to handle externally. I don't think I have enough time/resources to implement it.
